name: expo_repository
description: The repo that handles expenses
publish_to: 'none' # <- Estaba mal escrito como "publis_to"
version: 0.0.1

environment: # <- Estaba mal escrito como "enviroment"
  sdk: '>=3.1.0 <4.0.0'

dependencies: # <- Estaba mal escrito como "dependencis"
  flutter:
    sdk: flutter

  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2
  # rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
